networks:
  healthycore_network:

services:
  postgres:
    image: postgres
    container_name: postgres_healthycore
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - healthycore_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_healthycore
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - healthycore_network
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:
